
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int comment = 7;
  public static final int genreport = 4;
  public static final int dollar = 27;
  public static final int archivo = 34;
  public static final int osbracket = 22;
  public static final int oparent = 11;
  public static final int tituloy = 31;
  public static final int titulox = 30;
  public static final int semicolon = 9;
  public static final int graficabarras = 21;
  public static final int titulo = 24;
  public static final int doublee = 14;
  public static final int iddouble = 20;
  public static final int integerr = 13;
  public static final int ejex = 25;
  public static final int stringg = 15;
  public static final int puntajegeneral = 29;
  public static final int cparent = 12;
  public static final int EOF = 0;
  public static final int equal = 16;
  public static final int id = 3;
  public static final int error = 1;
  public static final int multcomment = 8;
  public static final int definirglobales = 2;
  public static final int graficapie = 32;
  public static final int obracket = 5;
  public static final int colon = 10;
  public static final int cbracket = 6;
  public static final int graficalineas = 33;
  public static final int valores = 26;
  public static final int csbracket = 23;
  public static final int comma = 18;
  public static final int idstring = 19;
  public static final int compare = 17;
  public static final int puntajeespecifico = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "definirglobales",
  "id",
  "genreport",
  "obracket",
  "cbracket",
  "comment",
  "multcomment",
  "semicolon",
  "colon",
  "oparent",
  "cparent",
  "integerr",
  "doublee",
  "stringg",
  "equal",
  "compare",
  "comma",
  "idstring",
  "iddouble",
  "graficabarras",
  "osbracket",
  "csbracket",
  "titulo",
  "ejex",
  "valores",
  "dollar",
  "puntajeespecifico",
  "puntajegeneral",
  "titulox",
  "tituloy",
  "graficapie",
  "graficalineas",
  "archivo"
  };
}

