
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadoresjs;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int slash = 37;
  public static final int tkbreak = 23;
  public static final int equalsto = 25;
  public static final int tkdefault = 24;
  public static final int different = 26;
  public static final int plus = 34;
  public static final int require = 42;
  public static final int minus = 35;
  public static final int classes = 2;
  public static final int tkwhile = 19;
  public static final int doublee = 44;
  public static final int comma = 9;
  public static final int greaterthan = 28;
  public static final int loeto = 29;
  public static final int obracket = 3;
  public static final int let = 14;
  public static final int modulus = 39;
  public static final int lessthan = 27;
  public static final int cbracket = 4;
  public static final int tkswitch = 21;
  public static final int tkcase = 22;
  public static final int equal = 12;
  public static final int tkdo = 20;
  public static final int console = 41;
  public static final int var = 13;
  public static final int EOF = 0;
  public static final int cparent = 8;
  public static final int tkconst = 15;
  public static final int oparent = 7;
  public static final int error = 1;
  public static final int or = 32;
  public static final int pot = 38;
  public static final int colon = 6;
  public static final int multcomment = 47;
  public static final int comment = 46;
  public static final int stringg = 45;
  public static final int goeto = 30;
  public static final int id = 48;
  public static final int mult = 36;
  public static final int csbracket = 11;
  public static final int and = 31;
  public static final int not = 33;
  public static final int osbracket = 10;
  public static final int tkif = 16;
  public static final int integerr = 43;
  public static final int semicolon = 5;
  public static final int tkfor = 18;
  public static final int tkelse = 17;
  public static final int charr = 40;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "classes",
  "obracket",
  "cbracket",
  "semicolon",
  "colon",
  "oparent",
  "cparent",
  "comma",
  "osbracket",
  "csbracket",
  "equal",
  "var",
  "let",
  "tkconst",
  "tkif",
  "tkelse",
  "tkfor",
  "tkwhile",
  "tkdo",
  "tkswitch",
  "tkcase",
  "tkbreak",
  "tkdefault",
  "equalsto",
  "different",
  "lessthan",
  "greaterthan",
  "loeto",
  "goeto",
  "and",
  "or",
  "not",
  "plus",
  "minus",
  "mult",
  "slash",
  "pot",
  "modulus",
  "charr",
  "console",
  "require",
  "integerr",
  "doublee",
  "stringg",
  "comment",
  "multcomment",
  "id"
  };
}

